Traduccion Quinto Modulo: Methods and interfaces
gophers-latam/go-tour-es pull request #12
Opened 2023-07-28 03:33 UTC by ThiagoMowszet

Se crea este PR a partir del issue #7.
Se tradujeron las 26 paginas y los archivos *.go.

2023-08-02 19:25 UTC, Sirpyerre requested changes
Hola, te dejo algunos comentarios.

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +(Este es el mismo comportamiento que para cualquier otro argumento de función.)
Al leer esta oración no logro entenderla, creo que quedaría mejor así:
`Este comportamiento es igual para cualquier otro argumento de función.`

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +debajo del capo, los valores de interfaz se pueden considerar como una tupla de un valor y un
Mayúscula al iniciar una oración.

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +tipo en concreto:
Aquí no estoy seguro si debe llevar mayúscula, ya que en el original está en minúscula, aun así lo comento.

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +Tenga en cuenta que un valor de interfaz que contiene un valor concreto nulo es en sí mismo no nulo.
Esté párrafo también me resulta confuso, propongo el siguiente:
`Tenga en cuenta que un valor de interfaz que contiene un valor concreto nulo no es considerado nulo en sí mismo.`

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +(Cada tipo implementa por lo menos zero metodos.)
Aquí `zero` con `c`.

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +como un quad punteado.
En lugar de `quad` sería `cuarteto`.

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +metodo tal que `ErrNegativeSqrt(-2).Error()` retorne `"cannot`Sqrt`negative`number:`-2"`.
En el mensaje de retorno es mejor ponerlo en español así: `"No se puede calcular la raíz cuadrada de un número negativo`

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +El tipo `rot13Reader` es proporcionado para ti.
Sería: `es proporcionado por ti`

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +Conviértalo en un `io.Reader` implementando su método `Read`.
Conviértelo

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +[[https://golang.org/pkg/image/#Rectangle][`image.Rectangle`]], como él
Mejor así: 
```
image.Rectangle, ya que la declaración está dentro del paquete `image`
```

2023-08-02 19:25 UTC, Sirpyerre commented on tour/content/methods.article
> +Defina su propio tipo de `Imagen`, implemente [[https://golang.org/pkg/image/#Image][los métodos necesarios]] y llame a `pic.ShowImage`.
Define tu propio tipo de `Imagen`...

2023-08-04 13:28 UTC, ThiagoMowszet commented on tour/content/methods.article
> +tipo en concreto:
Si, es una continuación del texto por lo que no iría en mayúscula.

2023-08-04 13:29 UTC, ThiagoMowszet commented
Gracias por las correcciones @Sirpyerre.
Ya fue corregido todo lo indicado. Si esta todo ok, hacemos el merge.
Saludos! :goal_net:

2023-08-04 15:51 UTC, Sirpyerre requested changes
Hola, @ThiagoMowszet revisando más a fondo encontré otros errores. Te dejo los comentarios.
Saludos.

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods.article
> +metodo tal que `ErrNegativeSqrt(-2).Error()` retorne `"No` `se` `puede` `calcular` `la` `raíz` `cuadrada` `de` `un` `número` `negativo`: `-2"`
Método con acento.

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods/exercise-reader.go
> +// TODO: Agregar un metodo Read([]byte) (int, error) a MyReader.
método

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods/exercise-stringer.go
> +// TODO: agregar un metodo "String() string" a IPAddr.
método

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods.article
> +*Nota:* Una llamada a `fmt.Sprint(e)` dentro del método `Error` enviará el programa a un bucle infinito. Puede evitar esto convirtiendo `e` primero: `fmt.Sprint(float64(e))`.  ¿Por qué?
Que tal rescribir esté parrafo como sigue:

Nota: Una llamada a fmt.Sprint(e) dentro del método `Error` puede llevar al programa a un bucle infinito. Puedes evitar esto convirtiendo primero `e` en **float64**, así: `fmt.Sprint(float64(e))`. ¿Por qué?

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods.article
> +Cambie su función `Sqrt` para devolver un valor `ErrNegativeSqrt` cuando se le dé un número negativo
Cambiar la forma de dirigirse al lector:
Cambia tu función `Sqrt` para devolver un valor `ErrNegativeSqrt` cuando se le pase un número negativo.

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods.article
> +(Vea [[https://golang.org/pkg/image/#Image][la documentación]] para todos los detalles.)
Creo quedaría mejor: 

(Consulta [[https://golang.org/pkg/image/#Image][la documentación]] para obtener todos los detalles).

2023-08-04 15:51 UTC, Sirpyerre commented on tour/content/methods.article
> +Puede volver a la lista de [[/list][modulos]] para encontrar qué aprender a continuación, o continuar con la [[javascript:click('.next-page')][siguiente lección]].
**Puedes**
 **módulos**

2023-08-04 23:13 UTC, ThiagoMowszet commented
Gracias nuevamente @Sirpyerre!
Muy precisos y detallados los cambios. Procedí a ejecutarlos.
Saludos.

2023-08-05 00:05 UTC, Sirpyerre approved these changes

2023-08-05 00:28 UTC, merged